# Site settings
title: Alex Dykstra
description: Developer
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Alex Dykstra
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Software Developer
email: alex@alexdykstra.com
#twitter_username: lorem_ipsum
github_username:  sircodesalittle
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "UA-109288343-1"

exclude: ['package.json', 'src' , 'node_modules']
