# Site settings
title: Alex Dykstra
description: Developer
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "http://alexdykstra.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Alex Dykstra
user_description: Coming soon!
user_title: Software Developer
email: alex@alexdykstra.com
#twitter_username: lorem_ipsum
github_username:  sircodesalittle
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "UA-109288343-1"

exclude: ['package.json', 'src' , 'node_modules']
